### ISSUE TITLE
色を変更する

### ISSUE THREAD

**Issue by xketanaka** [NaCl-Ltd/intern-2023-A#4]
以下の赤い四角で囲った箇所の背景色を変えてください。

![image](https://github.com/NaCl-Ltd/intern-2023-A/assets/1905688/a8228bc7-d01c-469f-b856-b42ab24278ad)

色は「#EEEEEE」が良いです。（が、他に良さそうな色があれば提案ください。）

- ![#eeeeee](https://placehold.co/15x15/eeeeee/eeeeee.png) `#EEEEEE`

**Comment by mametaro99** [comment]
ホーム画面のプロフィール・投稿欄の背景色を変更しました。
